# Generated by Django 4.2.11 on 2024-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
